// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6I8o-vPqFZnJUUjkTNzQbLYwp9typKc',
    appId: '1:307849261215:web:8c0ae90e02d0811a6272aa',
    messagingSenderId: '307849261215',
    projectId: 'gymapp-ee822',
    authDomain: 'gymapp-ee822.firebaseapp.com',
    storageBucket: 'gymapp-ee822.firebasestorage.app',
    measurementId: 'G-95MCR9PQ3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMi5K7xX_S0REEcDTtrxWvsFW766qVaNA',
    appId: '1:307849261215:android:cf9b5853772cb5706272aa',
    messagingSenderId: '307849261215',
    projectId: 'gymapp-ee822',
    storageBucket: 'gymapp-ee822.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAl2tSNRpAnSY-95WxUrngzhXD03X2Kzo',
    appId: '1:307849261215:ios:7be91ad450e155026272aa',
    messagingSenderId: '307849261215',
    projectId: 'gymapp-ee822',
    storageBucket: 'gymapp-ee822.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAl2tSNRpAnSY-95WxUrngzhXD03X2Kzo',
    appId: '1:307849261215:ios:7be91ad450e155026272aa',
    messagingSenderId: '307849261215',
    projectId: 'gymapp-ee822',
    storageBucket: 'gymapp-ee822.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr6I8o-vPqFZnJUUjkTNzQbLYwp9typKc',
    appId: '1:307849261215:web:f1d8392249b451f26272aa',
    messagingSenderId: '307849261215',
    projectId: 'gymapp-ee822',
    authDomain: 'gymapp-ee822.firebaseapp.com',
    storageBucket: 'gymapp-ee822.firebasestorage.app',
    measurementId: 'G-2M83L4R690',
  );
}
